import {
  AFFILIATIONS,
  IFF_MODES,
  PLATFORMS,
  affiliationColor,
} from '../radarTypes'

export default function EntityPanel({
  entities,
  selectedId,
  onSelect,
  onChange,
  onDelete,
  onAdd,
}) {
  const selected = entities.find((e) => e.id === selectedId) || null

  function patch(field, value) {
    if (!selected) return
    const next = { ...selected, [field]: value }
    if (field === 'platform') {
      const p = PLATFORMS.find((x) => x.id === value)
      if (p) {
        if (!selected.speed_mps) next.speed_mps = p.speed
      }
    }
    onChange(next)
  }

  function affOf(e) {
    return e.affiliation || e.side || 'unknown'
  }

  function platOf(e) {
    return e.platform || e.entity_type || 'unknown'
  }

  function shortAff(a) {
    return AFFILIATIONS.find((x) => x.id === a)?.short || a?.slice(0, 3)?.toUpperCase()
  }

  return (
    <aside className="flex h-full w-80 shrink-0 flex-col border-r border-[var(--line)] bg-[var(--bg-panel)]">
      <div className="flex items-center justify-between border-b border-[var(--line)] px-3 py-3">
        <div>
          <div
            className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[var(--muted)]"
            style={{ fontFamily: 'var(--font-display)' }}
          >
            Entity feed
          </div>
          <div
            className="text-lg font-semibold leading-none text-[var(--text)]"
            style={{ fontFamily: 'var(--font-display)' }}
          >
            Targets
            <span className="ml-2 text-sm font-normal text-[var(--muted)]">
              {entities.length}
            </span>
          </div>
        </div>
        <button type="button" className="hud-btn hud-btn-primary" onClick={onAdd}>
          + Add
        </button>
      </div>

      <ul className="max-h-[36%] space-y-0.5 overflow-y-auto border-b border-[var(--line)] p-2">
        {entities.length === 0 && (
          <li className="px-2 py-8 text-center text-xs text-[var(--muted)]">
            No targets — Add, then click the map
          </li>
        )}
        {entities.map((e) => {
          const active = e.id === selectedId
          const aff = affOf(e)
          return (
            <li key={e.id}>
              <button
                type="button"
                onClick={() => onSelect(e.id)}
                className={`flex w-full items-center gap-2 rounded-sm px-2 py-2 text-left transition ${
                  active
                    ? 'bg-[var(--accent-dim)] ring-1 ring-[rgba(45,212,191,0.35)]'
                    : 'hover:bg-white/[0.04]'
                }`}
              >
                <span
                  className="inline-block h-2 w-2 shrink-0 rotate-45"
                  style={{ background: affiliationColor(aff) }}
                />
                <span className="min-w-0 flex-1">
                  <span className="block truncate text-sm font-medium">
                    {e.name || e.id}
                  </span>
                  <span
                    className="block truncate text-[10px] text-[var(--muted)]"
                    style={{ fontFamily: 'var(--font-mono)' }}
                  >
                    {platOf(e)}
                    {e.iff_enabled
                      ? ` · SQ ${e.squawk || '----'}`
                      : ' · IFF OFF'}
                  </span>
                </span>
                <span
                  className="shrink-0 text-[10px] font-semibold uppercase tracking-wider"
                  style={{
                    color: affiliationColor(aff),
                    fontFamily: 'var(--font-mono)',
                  }}
                >
                  {shortAff(aff)}
                </span>
              </button>
            </li>
          )
        })}
      </ul>

      <div className="flex min-h-0 flex-1 flex-col gap-2.5 overflow-y-auto p-3">
        {!selected ? (
          <p className="py-10 text-center text-xs leading-relaxed text-[var(--muted)]">
            Select a target. This app only publishes entity truth over UDP —
            radar/IFF blips are generated by the workplace simulator.
          </p>
        ) : (
          <>
            <Field label="Callsign">
              <input
                className="hud-input w-full"
                value={selected.name || ''}
                onChange={(ev) => patch('name', ev.target.value)}
              />
            </Field>

            <div className="grid grid-cols-2 gap-2">
              <Field label="Affiliation">
                <select
                  className="hud-input w-full"
                  value={affOf(selected)}
                  onChange={(ev) => patch('affiliation', ev.target.value)}
                >
                  {AFFILIATIONS.map((a) => (
                    <option key={a.id} value={a.id}>
                      {a.label}
                    </option>
                  ))}
                </select>
              </Field>
              <Field label="Platform">
                <select
                  className="hud-input w-full"
                  value={platOf(selected)}
                  onChange={(ev) => patch('platform', ev.target.value)}
                >
                  {PLATFORMS.map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.label}
                    </option>
                  ))}
                </select>
              </Field>
            </div>

            <div
              className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[var(--muted)]"
              style={{ fontFamily: 'var(--font-display)' }}
            >
              Kinematics
            </div>
            <div className="grid grid-cols-2 gap-2">
              <Field label="Lat">
                <input
                  type="number"
                  step="any"
                  className="hud-input w-full"
                  value={selected.lat}
                  onChange={(ev) => patch('lat', Number(ev.target.value))}
                />
              </Field>
              <Field label="Lon">
                <input
                  type="number"
                  step="any"
                  className="hud-input w-full"
                  value={selected.lon}
                  onChange={(ev) => patch('lon', Number(ev.target.value))}
                />
              </Field>
              <Field label="Alt m">
                <input
                  type="number"
                  step="any"
                  className="hud-input w-full"
                  value={selected.alt_m ?? selected.alt ?? 0}
                  onChange={(ev) => patch('alt_m', Number(ev.target.value))}
                />
              </Field>
              <Field label="Climb m/s">
                <input
                  type="number"
                  step="any"
                  className="hud-input w-full"
                  value={selected.climb_mps ?? 0}
                  onChange={(ev) => patch('climb_mps', Number(ev.target.value))}
                />
              </Field>
              <Field label="Heading °">
                <input
                  type="number"
                  step="any"
                  className="hud-input w-full"
                  value={selected.heading_deg}
                  onChange={(ev) => patch('heading_deg', Number(ev.target.value))}
                />
              </Field>
              <Field label="Speed m/s">
                <input
                  type="number"
                  step="any"
                  className="hud-input w-full"
                  value={selected.speed_mps}
                  onChange={(ev) => patch('speed_mps', Number(ev.target.value))}
                />
              </Field>
            </div>

            <div
              className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[var(--muted)]"
              style={{ fontFamily: 'var(--font-display)' }}
            >
              IFF / SIF
            </div>
            <label className="flex items-center gap-2 text-xs text-[var(--muted)]">
              <input
                type="checkbox"
                checked={!!selected.iff_enabled}
                onChange={(ev) => patch('iff_enabled', ev.target.checked)}
              />
              IFF enabled (reply to interrogations)
            </label>
            <div className="grid grid-cols-2 gap-2">
              <Field label="Mode">
                <select
                  className="hud-input w-full"
                  value={selected.iff_mode || '3A'}
                  onChange={(ev) => patch('iff_mode', ev.target.value)}
                  disabled={!selected.iff_enabled}
                >
                  {IFF_MODES.map((m) => (
                    <option key={m} value={m}>
                      {m}
                    </option>
                  ))}
                </select>
              </Field>
              <Field label="Squawk">
                <input
                  className="hud-input w-full"
                  value={selected.squawk || ''}
                  maxLength={4}
                  onChange={(ev) =>
                    patch('squawk', ev.target.value.replace(/[^0-7]/g, '').slice(0, 4))
                  }
                  disabled={!selected.iff_enabled}
                />
              </Field>
            </div>
            <div className="flex gap-4 text-xs text-[var(--muted)]">
              <label className="flex items-center gap-2">
                <input
                  type="checkbox"
                  checked={!!selected.mode_c}
                  onChange={(ev) => patch('mode_c', ev.target.checked)}
                  disabled={!selected.iff_enabled}
                />
                Mode C
              </label>
              <label className="flex items-center gap-2">
                <input
                  type="checkbox"
                  checked={!!selected.mode_4}
                  onChange={(ev) => patch('mode_4', ev.target.checked)}
                  disabled={!selected.iff_enabled}
                />
                Mode 4
              </label>
            </div>

            <button
              type="button"
              className="hud-btn hud-btn-danger mt-auto"
              onClick={() => onDelete(selected.id)}
            >
              Delete target
            </button>
          </>
        )}
      </div>
    </aside>
  )
}

function Field({ label, children }) {
  return (
    <label className="block">
      <span
        className="mb-1 block text-[10px] font-semibold uppercase tracking-[0.16em] text-[var(--muted)]"
        style={{ fontFamily: 'var(--font-display)' }}
      >
        {label}
      </span>
      {children}
    </label>
  )
}
